### ISSUE TITLE
Config panel Auto-Hide

### ISSUE THREAD

**Issue by mighelon** [kmscode/mRemote3G#13]
Hi,
the Auto-Hide feature of Config panel doesn't work, it stays open forever.
Thank you

**Comment by kmscode** [comment]
This doesn't happen on my systems or to any other users that I know of...

Try the following:
1. Close mRemtoe3G
2. rename the pnlLayout.xml to .old
3. Open mRemote3G
4. re-configuring the autohide and other layout options as desired.

If you still have problems attach both the pnlLayout.xml and .old files.

**Comment by mighelon** [comment]
you're completely right, now it works even on my system
maybe has been a temporary issue
thank you a lot!

m.
