### ISSUE TITLE
Unchecking 'Show Text' on 'External Tools Toolbar' doesn't work.

### ISSUE THREAD

**Issue by damiankaczkowski** [kmscode/mRemote3G#15]
As subject says. Right click on the 'External Tools Toolbar' and uncheck 'Show Text' and you will see it doesn't work. It is very useful feature if one got many external toolbars.

Btw. can't find the way to open closed ticket so just wanted to point out that #10 needs reviewing cause it is still not fixed. Thank you.

**Comment by kmscode** [comment]
The external app must have an image associated with it in order for only the image (and not the text) to be displayed.

Please send a screenshot of your toolbar. I might be able to set a default icon if we're not able to load one from the file properties.

Note: Tools.Misc - GetIconFromFile

**Comment by damiankaczkowski** [comment]
It seems that after fixing #10 all is good now. Please close this bug report. Thank you.
