### ISSUE TITLE
Feature request - filter connections instead of jumping to the first match.

### ISSUE THREAD

**Issue by damiankaczkowski** [kmscode/mRemote3G#18]
When you open the Connections sidebar there is small search form at the bottom of the Connections sidebar. Unfortunately current search form is not very useful - it doesn't filter anything - it just jumps to the first matching connection. If you got two connections with the similar name and want to jump to the second one then you got problem.

I propose to move the search form from the bottom to the top of the Connections sidebar and change the behavior of the form to filter all connections that match our search. This would be very handy when you got dozens or hundreds of connections. The search could support wildcards and extended or perl regexp for advanced users : ).

Please consider implementing this feature. Thank you in advance : ).

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
