### ISSUE TITLE
Improve RDP Smart Sizing Support

### ISSUE THREAD

**Issue by jcefoli** [kmscode/mRemote3G#20]
I'm not sure if this is possible because of the way mRemote integrates and handles the windowing/framing, or because this feature may only be available with full screen RDP in the native Windows client, but here goes:

Currently in mRemote, it doesn't look like the smart size option actually re-scales the window the same way the native Windows Remote Desktop client does.

### To Reproduce
1. Using the native Remote Desktop Connection (mstsc.exe) app, connect to a computer.
2. Make the connection full screen
3. On the connection toolbar, click the restore down to get a windowed version of that connection
4. Resize the window and note how the resolution remains the same on the remote connection, but the content scales with the window
5. In mRemote, create a new connection.
6. In the Config panel for that new connection, set "Resolution: Smart Size" (the default is Fit to Panel)
7. Connect to that in mRemote, with mRemote maximized
8. Resize the window smaller (Note how scroll bars appear rather than scaling)
9. Disconnect RDP connection
10. With non-maximized small mRemote window, connect to the RDP session
11. Maximize the mRemote window, note that window does not scale up

#### Actual
It looks like what's happening is that when "Smart Size" is selected for a connection in the config panel, it connects at a fixed resolution of the framed window. if the mRemote window size is decreased, scrollbars appear and the resolution of the remote connection remains locked. This essentially behaves the same as setting "Resolution: Fit to Panel" and "Automatic Resize: No" mRemote options, so maybe something is broken or was just never implemented properly.

* After step 9, scrollbars appear and the window content does not scale down to the frame size in mRemote.
* After step 11, the resolution is fixed and does not expand to the size of the frame in mremote

#### Expected
When initiating a new connection and the mRemote option "Resolution: Smart Size" is set:
* Upon connection, set the native display resolution for that current monitor, but use smart scaling to fit the content in the window
* Any time the window is resized, it will scale with the frame within mRemote

Thoughts? You can close this if it's not technically possible,

**Comment by kmscode** [comment]
I'm working on 1.94.2 which will have some RDP related updates. See #11. Once this is released (possibly later today????) try it out and let me know if you still have the same problems. Some screen shots of mRemote's behavior and expected mstsc behavior would be appreciated. I haven't used the Smart Size option personally so I would like to ensure that I have a good understanding of this.

**Comment by jcefoli** [comment]
I pulled and compiled, but it doesn't look like smart sizing is working (happy to retest on your official release in case I did something wrong). Despite the ActiveX control being updated, more logic is probably needed to get this working like the native RDP client. As you pointed out in #11, some commits from [this fork](https://github.com/karoberts/mRemoteNG) (Specifically the last few commits related to smart sizing), might be helpful to you.

Here are some examples:

### Native RDP Client (With Smart Sizing Enabled)
![smart sizing rdp](https://cloud.githubusercontent.com/assets/6618013/12682890/dd3e73c6-c683-11e5-8870-f5a7a49de983.png)
Looks like it sets an initial resolution of your local computer.. Then, if you size down the window, the entire desktop area scales to fit into the resized window.

### mRemote (With Smart Sizing Enabled), Not Scaling Down:
![smart sizing mremote](https://cloud.githubusercontent.com/assets/6618013/12682889/dd3df414-c683-11e5-8e04-d250c71e4902.png)
Note the scrollbars. The expected behavior is to scale the whole desktop to fit in the frame and not have scrollbars. This is how the native RDP client behaves with smart sizing option unchecked.

Let me know if you need any more info.

**Comment by kmscode** [comment]
Thanks for the screen shots...

Didn't release since I didn't have a chance to test it as much as I would like since I'm replacing those other libraries. I also needed to test on some older Windows version. Did find a Win 7SP1 system to test with and it looks OK... So I'll most likely release in a little bit.

Doubt you missed anything. I'll work on a pull request for the other code and see about getting that in sometime next week... Flag that as 1.94.3.

Thanks for the feedback and testing!

**Comment by jcefoli** [comment]
Thanks! I'm not fully sure that the other code does exactly what I'd describing. I cloned the other fork but it didn't compile for me. so I couldn't test it. Don't apologize. It probably was never implemented properly and isn't related to you updating the activex control (although it may not have been possible with the old control, and still might not even be possible). I'm merely suggesting this as an enhancement.

**Comment by kmscode** [comment]
Fixed in 3f54842cc186a000151575665fd2e87213ec6617

**Comment by kmscode** [comment]
@jcefoli Did you have a chance to test this at all? 

I have a test build with this compiled in:
https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.40622

However, based on my testing, it doesn't seem like smart size works when selected "by default", but setting up smart size by right clicking on the connection tab does set smart size as expected. I'm still messing around with it a bit though.

Let me know if you have any additional feedback/testing results - feel free to reopen the bug report if needed.

**Comment by jcefoli** [comment]
Funny you say this. I was about to file exactly what you said against 1.94.2. 

It works perfectly for me in 1.94.2.40622. When I set my options to "Resolution: Smart Size" and connect to an RDP session, right clicking on the connection tab already has smart size toggled and the window auto resizes. This seems like correct behavior to me.
