### ISSUE TITLE
Allow custom configuration directories

### ISSUE THREAD

**Issue by Es-Paul** [kmscode/mRemote3G#22]
My workstation security is setup so that executable will only run executables in "C:\Program Files" and "C:\Program Files (x86)".  It is also setup so that programs can't write to these directories.

It would be nice if we could set a custom directory for mRemote3G to write to the .xml, .log, .backup and .config files, so that I can set this to a path under %APPDATA%, much like mRemoteNG does.

**Comment by kmscode** [comment]
Eventually I would like to build a full installer with update checks much like the old mRemoteNG had. However, that is not something that I have time to do at the moment. However, this might be an easy enhancement to build into the portable version in the meantime. I'll look into it. No ETA.

**Comment by kmscode** [comment]
@Es-Paul 

Test out the installer and let me know how it goes:
https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.40622

**Comment by Es-Paul** [comment]
Hi kmscode,

The new installer worked perfectly and the program is working within the security settings of my environment.

Thanks a lot for this, I'm now switching from mRemoteNG :)
