### ISSUE TITLE
High DPI screens

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#23]
Some items are displayed incorrectly with High DPI screens.  I'm suing the surface book and some items are crunched.  Default is like 200% but I use 150-175% scaling

**Comment by kmscode** [comment]
Check out #11 and #20 - semi-similar...

What build are you running? Have you attempted the [latest prerelease build](https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.40622)?

Screenshots of mRemote vs mstsc may also be helpful... However, I can't find any options in the RDP APIs to adjust any High DPI options.

**Comment by Silent-Joker** [comment]
I am sorry I should have specified but I was in a rush end of day!..  I mean with Mremote not RDP.  I'm using version: 1.94.2.40630  Some text is messed up etc.  2 examples are on the about page.  The word Portable on the top black bar looks to not scale right as its to big for what looks to be the text area.  same with the word "mRemote3G" it covers up the first lin
![mremote3g_highdpi](https://cloud.githubusercontent.com/assets/17053210/12799615/b1e6baee-ca9d-11e5-895f-911dfe2a7909.png)
![options_screen](https://cloud.githubusercontent.com/assets/17053210/12799616/b1eacb70-ca9d-11e5-8123-6a0d25436c5f.png)
![options_screen2](https://cloud.githubusercontent.com/assets/17053210/12799614/b1e2e388-ca9d-11e5-9229-6161640b0dcd.png)


e of text saying the version.

**Comment by kmscode** [comment]
OK... Very clear. Thanks for the screen shots!

Any thing that is truly impacting base functionality here?

I complied in the "dpiaware" flag to prevent the UI as a whole from being fuzzy. Reference 41b1122dafd0ece41617ef43a418ae6c92793810

However, I didn't do anything to actually make this dpiaware. I will look into it, but it will most likely be backburnered for a little while as it will likely be a significant effort. Though I may see about simply disabling the dpiaware (since I'm lying anyway) and see if that resolves the issue (I suspect it should).

**Comment by Silent-Joker** [comment]
Nope this is a stupid cosmetic issue please don't slow down work for this hehe.  I love that your updating this project.   do you have a feature request section?

**Comment by kmscode** [comment]
@Silent-Joker Open a new issue with all details. I'll review and flag it as an enhancement accordingly.

**Comment by njeske** [comment]
I checked this out myself, just to see if I had the same issue.  I have a 3K screen on my laptop, and use 2 x 2K monitors when I'm docked.  My display settings in Windows 10 are for 100% scaling (no scaling), and I don't have any squished items in any of the mRemote3G screens.  My be more related to Windows scaling than just having high DPI screens.

**Comment by Silent-Joker** [comment]
Correct its from the default scaling when using anything other than 1080 screen.  

Also another issue with scaling is with the help documents.  I have fixed this for me by simply editing the .css file.  Just change this code.

The graphics are different sizes so it may look normal in both images

- old -
**Line 15:	font-size: 11px;**
![bad](https://cloud.githubusercontent.com/assets/17053210/12927090/36ae238a-cf34-11e5-9997-a910b72492fd.png)

- new -
**Line 15:   	font-size: 1em;**
![good](https://cloud.githubusercontent.com/assets/17053210/12927005/e19db19e-cf33-11e5-9e83-aed278f9c7db.png)

I know most people probably never look at these buy I'm sure some do.

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
