### ISSUE TITLE
inheritance issue

### ISSUE THREAD

**Issue by federicozanardi** [kmscode/mRemote3G#25]
consider this situation:

customer1 (with credentials set to user1)
- server1
- server2
- folder DMZ (with other credentials)
--serverd1
--serverd2
- server3 (please note it is child of customer1...)

server3 should connect with creds from customer1, instead mremote use creds from DMZ folder

**Comment by kmscode** [comment]
Duplicate of #9

**Comment by federicozanardi** [comment]
ops ok :)
