### ISSUE TITLE
[Request] Credential Manager

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#26]
The one feature I wish NG had before it went stale was being able to save a set of credentials and link to them like inheritance.  So If you add a custom folder under connections called Credentials and then when you go in this folder you can only add a credential object that is username,password,domain.  This would then be linkable under the current username items as a dropdown that says use Credential manager and then allows you to select from a dropdown of the usernames under that Special Folder.

When you choose use Credential manager it hides the default username,password,domain fields and doesn't use them.
![linked credentials](https://cloud.githubusercontent.com/assets/17053210/12851876/42738a44-cbfa-11e5-88bb-d72bd08de69c.png)

**Comment by Silent-Joker** [comment]
my goal of this is to use linked credentials under 1 folder.  So when I login to multiple devices but I use the same 3 accounts.  This way when I update my password I don't need to update the object each time.  I just update the Credential object store under the credentials folder.  

Its cause I hate to break up my "Network" folder to be per username etc.

**Comment by kmscode** [comment]
So just to summarize, you want to be able to use a credential manager rather than inheritance. This way you can choose the credentials to connect to the server as needed (possibly 2 or more credentials for a single server)?

**Comment by Silent-Joker** [comment]
Being able to choose a saved credential instead of inheritance yes.  Not more than one login per connection object.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-184
