### ISSUE TITLE
[Request] Open Multiple Connection Files

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#27]
This would be nice.  I like to seperate them by company right now that I have.  But if you do credential manager please only allow linking to credentials saved per connection file not a global one.

If this requires a rewrite of alot of core code than may I suggest changing the connection files to be .mr3g so we can associate them with mremote to open as default program instead of .xml.  Than I can just shortcut the files to load the connection.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
