### ISSUE TITLE
Appdata\mRemoteNG user.config files

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#28]
There seems to be 1 log file that got created here that maybe a find and replace missed the name.  Looking in the folders shows the user.config files under the version I had running.

1.94.2.40630
![capture20160207094940610](https://cloud.githubusercontent.com/assets/17053210/12872993/4a083796-cd80-11e5-88af-d335cef47f90.png)

**Comment by kmscode** [comment]
This looks like it's going to be a full refactor of the code. Which so far has been a massive headache (even with a pretty awesome tool to assist in that). I would like to clean this all up though.

**Comment by Silent-Joker** [comment]
no biggie its not a major issue I have OCD :)
