### ISSUE TITLE
[Request] MySql Support

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#29]
If its easy to add support for please enable or add MySQL support and not just MS SQL.

**Comment by kmscode** [comment]
The MS SQL support was experimental in mRemoteNG. Not sure how stable it is/was. 

Flagged as enhancement.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-793
