### ISSUE TITLE
Error code 3334

### ISSUE THREAD

**Issue by DaFr0g** [kmscode/mRemote3G#30]
Thought this issue where fixed in this version, but seems it's not so i will report it.

It's the same issue as here: https://mremoteng.atlassian.net/browse/MR-582 

WarningMsg
10-02-2016 09:50:44
RDP disconnected!

The session is interrupted due to a protocol error. Try to connect to the remote computer again.
Error code 3334.

**Comment by kmscode** [comment]
Duplicate of #19
