### ISSUE TITLE
windows installer mremote3G 1.94.2 still says mRemoteNG

### ISSUE THREAD

**Issue by wardcomm** [kmscode/mRemote3G#32]
windows installer mremote3G 1.94.2 still says mRemoteNG
and
there is a .NET Framework 4.6 requirement that you find out at the end setup

**Comment by kmscode** [comment]
@wardcomm the install is flagged as "prerelease" for a number of reasons - these are included. :smile: 

I have been looking into the possibility of lowering the .net requirement to 4.0. I haven't found anything that specifically requires 4.6 as of yet.

I will update the readme with requirements when I do the next release.

**Comment by jcefoli** [comment]
@kmscode Bummer. I like the idea of latest and greatest, especially if anyone wants to refactor anything and take advantage of new features in the latest .NET. Windows 10 includes the .NET 4.6 framework by default and it's a decent OS that Microsoft is pushing hard for everyone to upgrade to. People should just install the 4.6 framework or upgrade to Windows 10.

**Comment by kmscode** [comment]
@jcefoli "looking into the possibility" - doesn't mean it's happening (or anytime soon!)... :stuck_out_tongue_winking_eye: 
Even if I did set it to requiring 4.0, the 4.6 version still satisfies this requirement. You'll still be latest and greatest on your system.

Detecting the version for 4.6 isn't 100% straightforward as it is with previous versions...
https://msdn.microsoft.com/en-us/library/hh925568%28v=vs.110%29.aspx#net_b

But I'll look into adding the checks on the installer if possible.

**Comment by kmscode** [comment]
@jcefoli for the record, can't set it any lower than 4.0 as we are using some 4.0 specific features.
