### ISSUE TITLE
VirtusTotal report malware 

### ISSUE THREAD

**Issue by johoya** [kmscode/mRemote3G#33]
VirusTotal.com report malware in those files from mRemote3G-1.94.2.34463.zip

1. mRemote3G.exe   HEUR/QVM03.0.Malware.Gen  by  Qihoo-360
2. PuTTYNG.exe       Troj.PSW32.W.Agent  by  AegisLab

**Comment by kmscode** [comment]
1 "bad" result out of 55 tests for each of those binaries. I'm going to call those "false positives". 

Scanned locally with McAfee VirusScan Enterprise 8.8. No threats found.

Feel free to do a code review and/or build from source. [PuTTYNG source can be found here](https://github.com/kmscode/PuTTYNG)

**Comment by Silent-Joker** [comment]
Here is an update...

Stable release has 1/55 flag but the pre release has 5/55

2 pre release version:
https://www.virustotal.com/en/file/ddc91c7626a637b3f1c2915b5ebc1cdbea767d8226f0af5b162da6268900fdb3/analysis/1458827001/

Stable release:
https://www.virustotal.com/en/file/5d7909abafcc99c583fb8a37635dc4a0ea600b9468504ebb7c66f25381a67afa/analysis/1458827218/

**Comment by kmscode** [comment]
False Positives are common with Anti-Virus software. [VirusTotal admits this itself](http://blog.virustotal.com/2015/02/a-first-shot-at-false-positives.html).

[Additional false positive details/tips/tricks](http://www.howtogeek.com/180162/how-to-tell-if-a-virus-is-actually-a-false-positive/)

Being the one man shop that I am, I can't register with VirusTotal as a trusted source. There's really not much I can do. Visual Studio complies the code and those Anti-Virus vendors flag it as a virus. 

As noted previously, the only suggestion that make if you are overly concerned about the saftey of this code would be to do your own code review and/or compile and run your own copy of the code. Or simply compile it yourself and test that version on VirusTotal. I use "BUILD.CMD" to compile the source and create packages.
