### ISSUE TITLE
RDCMan 2.7 compatibility

### ISSUE THREAD

**Issue by starks** [kmscode/mRemote3G#34]
I don't think the 2.7 schema is supported.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-862
