### ISSUE TITLE
Panels reset after program restart

### ISSUE THREAD

**Issue by limpsobaka** [kmscode/mRemote3G#36]
After program restart panels resets to their default layout:
Before restart:
![2016-02-24 11-54-16 mremote3g - confcons xml](https://cloud.githubusercontent.com/assets/17448604/13280186/8799ba1a-daed-11e5-8bde-cdab75c567da.png)

After restart:
![2016-02-24 11-56-03 mremote3g - confcons xml](https://cloud.githubusercontent.com/assets/17448604/13280202/9d29e012-daed-11e5-9086-a0b273437769.png)

Ver. 1.94.2.34463

**Comment by kmscode** [comment]
I've encountered similar problems as well. Haven't gotten to the bottom of it yet.

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
