### ISSUE TITLE
MSSQL things

### ISSUE THREAD

**Issue by DaFr0g** [kmscode/mRemote3G#38]
This is about the MSSQL feature.

It is pretty stable as it is now, been running with it for several years now(mRemoteNG, haven't changed to 3G yet).

during everyday usage of mRemote with MSSQL, i would recommend to use an read only user especally in multi teams since mRemote writes to the DB every time you make a change amd if more than one writes to the DB at once it will break.

The fix i use is to have a portable version with a read/write user for use when i need to change things, everyday usage i work with the installed version on an read only user, this is pretty stable, haven't had any crashes on this so far.

Some points that bugs me:
Changes of the DB makes the list bounce and unfold on the other mremotes(read only), dosen't collapse itself. this is due to a timer that reloads the DB every xx sec(I have disabled this on my version, and only use Ctrl+O to reload list after change), i also added an collapse trigger on the reload function even tho an rember state would have been better.

Features that would be nice on the MSSQL function:
Option to change from read/write to read only mode.
Option to change the auto reload freq, even disable it.
Rember list view at reload

**Comment by kmscode** [comment]
The MSSQL feature was listed as experimental and I suspect wasn't fully designed with multiple users involved.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-548?jql=status%20%3D%20Open%20AND%20text%20~%20%22sql%22
