### ISSUE TITLE
PUTTYNG: support storing sessions and host keys on file like portaputty and putty tray

### ISSUE THREAD

**Issue by dpeddi** [kmscode/mRemote3G#39]
Request for enhachement:

It would be nice if you would support the storing of sessions and host keys on file like portaputty and putty tray.

This would be really useful for portable installation

Obviously in a second stage mremote3g should support reading sessions settings from file.

Thank you for giving a new life to mremoteng! Regards

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-357
https://mremoteng.atlassian.net/browse/MR-404
