### ISSUE TITLE
ERROR- RDP SetProps failed!

### ISSUE THREAD

**Issue by khaoohs** [kmscode/mRemote3G#40]
Error when attempting to RDP.

From the mremote log:

`2016-03-08 10:47:35,059 [1] ERROR- RDP SetProps failed!
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.AxHost.CreateWithLicense(String license, Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32 state)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at mRemoteNG.Connection.Protocol.RDP.SetProps()`

Windows error message:
`************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.AxHost.CreateWithLicense(String license, Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32 state)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
mRemote3G
    Assembly Version: 1.94.2.23810
    Win32 Version: 1.94.2.23810
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/mRemote3G.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
mRemote3G.resources
    Assembly Version: 1.94.2.23810
    Win32 Version: 1.94.2.23810
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/en-US/mRemote3G.resources.DLL
----------------------------------------
MagicLibrary
    Assembly Version: 1.7.4.1
    Win32 Version: 1.7.4.1
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/MagicLibrary.DLL
----------------------------------------
PSTaskDialog
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/PSTaskDialog.DLL
----------------------------------------
log4net
    Assembly Version: 1.2.14.0
    Win32 Version: 1.2.14.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/log4net.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
FilteredPropertyGrid
    Assembly Version: 1.0.2258.31541
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/FilteredPropertyGrid.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
AxInterop.MSTSCLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/AxInterop.MSTSCLib.DLL
----------------------------------------
MSTSCLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/mRemote3G/MSTSCLib.DLL
----------------------------------------`

**Comment by kmscode** [comment]
What version of Windows are you running? Do you have RDP 8.1 (or later) installed (it's generally delivered as an "optional update" from windows update if I recall correctly)?

Can you export the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\ registry key?

**Comment by khaoohs** [comment]
I tried installing the Win 7.1 update, but the executable said it was not applicable.

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client]
"Version"="4.6.00081"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"InstallPath"="C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"
"Release"=dword:00060051

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client\1033]
"Version"="4.6.00081"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:00060051

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full]
"Version"="4.6.00081"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"MSI"=dword:00000001
"Servicing"=dword:00000000
"InstallPath"="C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\"
"Release"=dword:00060051

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033]
"Version"="4.6.00081"
"TargetVersion"="4.0.0"
"Install"=dword:00000001
"Servicing"=dword:00000000
"Release"=dword:00060051

`

**Comment by kmscode** [comment]
Did you attempt to install this update:
https://support.microsoft.com/en-us/kb/2923545

What version of RDP is currently installed: https://technet.microsoft.com/en-us/library/cc736828%28v=ws.10%29.aspx

**Comment by khaoohs** [comment]
Says 7.1 supported.

I have Win 7 SP1 installed.

When i attempt to install the 2923545 update, it says Update is not applicable to my Computer.

**Comment by kmscode** [comment]
You need to get that to say "8 supported" at a minimum. You have to get that update installed. Make sure you're installing the correct one - x86 for a 32 bit version of Windows and x64 for a 64 bit version of Windows (check that in Control Panel -> System).

[This thread](http://answers.microsoft.com/en-us/windows/forum/all/latest-windows-update-for-windows-7-kb2923545/c7b7a43a-4c2f-4942-af48-fe11e1ed7337?auth=1) has a number of suggestions for troubleshooting the installation of the update.

**Comment by khaoohs** [comment]
OK, i'm running out of options to attempt to install this Windows update, as this is a corporate managed PC image. 

Is the RDP 8.1 support necessary for the functioning of the app? Is there a build available without the RDP 8.1 support?

**Comment by jcefoli** [comment]
Can we catch the exception and at least prompt that RDP 8.1 is required, and maybe provide a link to the installer?

**Comment by kmscode** [comment]
@khaoohs - RDP8 is required in 1.94.2 and later.
[1.94.1](https://github.com/kmscode/mRemote3G/releases/tag/1.94.1) should work for you. But that only has a portable build.

mRemote3G technically only requires RDP8, so [this update](https://support.microsoft.com/en-us/kb/2592687) make correct the problem if you can get it installed. That one has some pre-reqs though. I'd have to build a system to apply this older update to validate - which I will attempt to do, but don't have any ETA for that.

Both 8.0 and 8.1 updates are well over 2 years old and address a number problems and security concerns. I would hope that your security team would allow those to be installed. Maybe check with your local IT group for assistance in getting them installed if you do not have appropriate access on your system.

@jcefoli Good idea. I'll see about adding it to the code and possibly the installer as well.

**Comment by khaoohs** [comment]
@kmscode, Thank you, i was able to successfully install the 8.0 update and it's pre-requiste. Thank you for the assistance and for keeping mremote alive.

**Comment by kmscode** [comment]
mRemoteNG does prereq checks for these fixes.
