### ISSUE TITLE
could we integrate with cygwin

### ISSUE THREAD

**Issue by wardcomm** [kmscode/mRemote3G#42]
could we integrate with cygwin. so that cygwin window users can have multiple tabs. similar to mobaxterm.

**Comment by kmscode** [comment]
Could you please provide some more details and/or screen shots of what you are looking for?

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
