### ISSUE TITLE
Help > Announcements causes app to crash

### ISSUE THREAD

**Issue by aplocher** [kmscode/mRemote3G#43]
Version 1.94.2.34463

When clicking the "Announcements" menu item inside the "Help" menu, the application crashes with the following event log entry:

```
Application: mRemote3G.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UriFormatException
   at System.Uri.CreateThis(System.String, Boolean, System.UriKind)
   at System.Uri..ctor(System.String)
   at mRemoteNG.App.Update.GetAnnouncementInfo()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by kmscode** [comment]
This should be an easy one. @aplocher you don't want to fix it??? :wink:

**Comment by kmscode** [comment]
Fixed in b71ae229fb2ae867430f0d85c48480ae3d2fd2ea

**Comment by aplocher** [comment]
Oops sorry, I've been up for almost 3 full days without sleep working on another project :-/ I'll be happy to do submit some pull requests soon.  

In fact, I have a nice change I've been wanting to finish up that completely overhauls the Connections TreeView and makes the search feature more of a first class citizen with it positioned above the TreeView and far more usable.  This was a while ago but I think it's pretty much done...

It was modeled after Visual Studio's Solution Explorer, with incremental search.  I believe I even copied the hotkey (CTRL+ semicolon), and instead of just selecting the top result, it actually incremental filters the list down and supports full keyboard navigation. So you can filter it down to a set of results like "PROD" shows all prod servers, and then select the 3rd result by hitting the down-arrow key 3 times and then hit enter to connect.

I'll need to dust off that code and check it in and submit a Pull Request...  Will do this weekend :)

Oh, but... (not sure if this is a problem) it's in a separate ancillary C# project.  I was starting to rewrite portions of it in a separate C# project and just wire the entry points up from VB, with the intention of eventually fully porting it to C#.  I despise VB

**Comment by kmscode** [comment]
Yeah... I'm not digging VB either these days. I'm thinking about fixing a few more things, releasing 1.94.4 and then creating a branch to convert to c#. I was looking at some BS plugins to assist with the bulk convert. I was able to score a free open source license for ReSharper which would likely help clean things up after the convert. 

Any help would be appreciated. Been busy myself as well so I only get an hour here or there to try to work on  this. :-D

**Comment by kmscode** [comment]
That should say V S not B. That's what I get for replying from my phone...
