### ISSUE TITLE
External tools problem when right clicking on connection tab multiple times.

### ISSUE THREAD

**Issue by damiankaczkowski** [kmscode/mRemote3G#45]
Hello. Regarding issue #16 . The bugfix causes some unexpected behavior. When you open the new connection and right click multiple times on connection toolbar/tab like shown on origin report video and then show external tools from context menu you will spot that some external tools entries are missing. On every right click one entry will be removed. Such behavior if fully reproducible.

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
