### ISSUE TITLE
Option to Specify Default Connection File Location

### ISSUE THREAD

**Issue by jcefoli** [kmscode/mRemote3G#46]
It would be nice if an option was added in settings to specify which connection file to load at startup. This would be useful for saving a file to OneDrive, so it can be shared in the cloud. I know the SQL Server feature exists, but this assumes everywhere I use mRemote3G has network access to that SQL Server. For a lot of IT people with strict firewall rules, this is not practical (varying network segments, opening SQL Server to the public internet, etc.)

Something like this in the GUI:
( ) Default
( ) Custom Location:  _______________ [Browse ...]

**Details:**
- The behavior of "Default" would be to load the connection file from the exe directory for the portable version or %appdata%/MRemote3G for the installed version.
- Even if a location is specified, backups should still be stored in exe directory for the portable version or %appdata%/MRemote3G for the installed version.
-If the file is unavailable at startup (manually deleted), it should prompt you to load from a saved backup and recreate the connection file in the path set in the Custom Location.

This could introduce concurrency issues if the app is running in multiple locations and the file is saved/ synced to the cloud while multiple instances are running. Not sure the best way to handle that one...

How is this implemented currently? In the File menu, there is an option to open another connection file. I assumed that if I opened a file in another location, it would always load that file on subsequent mRemote3G launches. However, it looks like it switched back to using the default connection file. Maybe a simpler implementation would be to just skip the GUI and remember the last location of the file?

What do you think?

Thanks again for keeping this project alive. I know you don't have all the time in the world to work on it, but maybe others will pick up some of these work items in the future.

**Comment by kmscode** [comment]
Have the custom config file location would be useful.
Something in the options menu for the xml location should be pretty straight forward.

If a prompt on startup were to be added, it would also be optional (and off by default).

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
