### ISSUE TITLE
about icon on folder

### ISSUE THREAD

**Issue by dsstorm** [kmscode/mRemote3G#48]
Sorry for my bad English.
You can make these icons are displayed instead of certain folders ?
Otherwise there is no point in these icons .

![image](https://cloud.githubusercontent.com/assets/18022579/13976727/c0bcab62-f0d3-11e5-82f0-d275ca38547b.gif)

**Comment by bamanzi** [comment]
+1.

And IMHO the connection node should display this icon rather than the PLAY/PAUSE icon (maybe an overlay icon or bold text would be better for indicating the connection status).

**Comment by kmscode** [comment]
I'll look into the ability to change the folder icon.

@bamanzi feel free to open another issue about an overlay. The play/pause icons are here to stay, but some sort of overlay or a red/green halo around the connection specific would be nice.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
