### ISSUE TITLE
[Request] Split-view

### ISSUE THREAD

**Issue by FJerusalem** [kmscode/mRemote3G#49]
It would be great to be able to split the current connection-view; for example when configuring cluster-services it is nice to see the output on one screen without having to switch from one tab to another.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
