### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by MattiasDV** [kmscode/mRemote3G#50]
Sorry if this is the wrong place to ask, but when will there be a new (pre)release?

**Comment by kmscode** [comment]
@MattiasDV I'm working on fixing #5 and #40 (which is just some added protections in the logs and code) at an absolute minimum before the next release.

I don't have any specific ETA. I work on this as much as I can in my free time. However, I am hoping for sometime in April.

While GitHub is fantastic, they don't really give you any area outside of issues / pull requests to communicate and interact with others/users about the overall project from what I can tell.

**Comment by kmscode** [comment]
#5 has been a particular pain to diagnose. But I'm fairly confident that I've at least narrowed it down the proper area of code. I just can't seem to find a proper solution that doesn't break something else.
