### ISSUE TITLE
sftp; ftp support or and termian (cmd)

### ISSUE THREAD

**Issue by willstdueswissen** [kmscode/mRemote3G#52]
Simple question.
Can you support sftp and ftp.
If you support terminal, i can also use a terminal ftp library.
I dislike the popout of an external software.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-281
