### ISSUE TITLE
Error i git when start mremote3g

### ISSUE THREAD

**Issue by wardcomm** [kmscode/mRemote3G#53]
when i tried to run i got this

[mremote3g error.zip](https://github.com/kmscode/mRemote3G/files/192178/mremote3g.error.zip)

**Comment by kmscode** [comment]
@wardcomm - sorry for the delayed response. I thought I had replied when I initially looked at this, but clearly I did not.

I haven't found anything particularly wrong in the code just yet. 

Does the C:\users\jcward\AppData\Roaming\mRemote3G\confCons.xml file exist? If so, try renaming it to .old and see if that will allow mRemote to start.

Does the C:\users\jcward\AppData\Roaming\mRemote3G\mRemote3G.log exist? Could you please attach that to the issue as well?

Thanks...

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
