### ISSUE TITLE
Windows Security Setting "System cryptography: Use FIPS compliant algorithms for encryption..." is enabled

### ISSUE THREAD

**Issue by Sergong** [kmscode/mRemote3G#56]
mRemote3G still has the same error as the last mRemoteNG version. 
See this link:
https://support.microsoft.com/en-us/kb/811833

Unfortunately this means I can no longer use it...

Any idea if support for the above is planned?

**Comment by kmscode** [comment]
Could you provide a screen shot of the error and/or the mremote3g.log?

I will look into this, but based on a first quick read of that document I'm not sure why exactly you would be having problems.

mRemote3G requires RDP Client 8 or later (article point out 5.2 or later).

I'll have to look into the APIs to see if there is any way to change the encryption options on the client connection...

**Comment by jcefoli** [comment]
Are you saying you have FIPS compliant mode enabled and mRemote3G does not work, but works if you disable it?

Why do you need that? It's not recommended: http://www.howtogeek.com/245859/why-you-shouldnt-enable-fips-compliant-encryption-on-windows/

**Comment by Sergong** [comment]
![image](https://cloud.githubusercontent.com/assets/653185/14760931/6aa68fc2-0951-11e6-8e82-0d8c3c653bc8.png)

Thanks for providing some reasons on why I don't need. However, there will be cases where people are forced to use it, so if it is possible to support this, that would be great.

The OS I'm running on is Windows 10 build 10586 and this message comes up because of this registery setting:
HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy being set to 1.

mRemote[3|N]G just quits after clicking OK to acknowledge the message.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-637
