### ISSUE TITLE
DPI and MSTSC

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#57]
Maybe put a setting in Mremote to toggle the manifest file so we can enable or disable the awareness so RDP is better on high dpi screens.  I use manifest file for mstsc but mremote doesn't use it so I needed to edit your file as well.

http://www.blackforce.co.uk/2016/04/18/remote-desktop-rdp-resolution-on-a-surface-book

Disable DPI aware so RDP is better on High DPI screens.

<asmv3:application xmlns="urn:schemas-microsoft-com:asm.v1">
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>false</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>

**Comment by kmscode** [comment]
DPI aware is currently disabled. I think it needs to be enabled, but also make the application DPI aware.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature

See:
https://mremoteng.atlassian.net/browse/MR-788
https://mremoteng.atlassian.net/browse/MR-699
