### ISSUE TITLE
Folder Name in Tab Title

### ISSUE THREAD

**Issue by unze** [kmscode/mRemote3G#58]
it would be nice if there was an option to display the parent folder name in the tab-title as extension to the connection name

![Image](http://abload.de/img/unbenannt7pjk0.png)

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Feel free to report any new enhancement requests here:
https://mremoteng.atlassian.net/wiki/display/MR/Request+a+Feature
