### ISSUE TITLE
Connections & Config panels not preserving width when using Auto-Hide

### ISSUE THREAD

**Issue by thecosmictrickster** [kmscode/mRemote3G#6]
I have the Connection & Config panels on auto-hide. I size them to what I want. When I restart mRemote, the sizes are back to default or possibly what they are set to before auto-hide is enabled.

**Comment by kaymer327** [comment]
A very quick look at the code... It seems the pnlLayout.xml file isn't properly loaded for the portable version. Will review/test further.

**Comment by kaymer327** [comment]
Please provide me with further details/screenshots of how you would like this to be saved and I can review further and/or post an issue with DPS if necessary.

**Comment by thecosmictrickster** [comment]
Basically, if I have the Connection and/or Configuration panels set to auto-hide, I [still] want to be able to resize them as required and have that new size preserved between restarts of the application (i.e. whatever the size of those panels was at the time the application was shut down, that should be the size when I start it up again). The same is true if I am not using auto-hide; whatever the size is when the application is shut down should be the size used when started up again.

**Comment by kmscode** [comment]
@thecosmictrickster @damiankaczkowski Could you please test the [latest pre-release](https://github.com/kmscode/mRemote3G/releases/tag/1.94.2.34463) to see if this still happens? This contains a new dockpanelsuite library.

**Comment by Silent-Joker** [comment]
I seen this notification and I wanted to let you know it saves for me but now its harder to use.  Scaling issue.  I can use it but its small.

**Comment by thecosmictrickster** [comment]
It's not working for the portable version. I haven't tried the normal version.

**Comment by Silent-Joker** [comment]
I used portable and it saves.  You mean if you set the width half the screen and it hides you go back to it and it's small?  From the left side of screen?

**Comment by damiankaczkowski** [comment]
HI. I have tested 1.94.2.34463 (zip) and 1.94.2.34470 (portable zip) and it doesn't work. Tested on Win7 SP1 Pro.

**Comment by Silent-Joker** [comment]
I just wana make sure I was saying the same thing.  Mine saves this width setting and hides and restored perfectly.

Version: .34470 (portable)
Windows 10 Enterprise: 10586.104
Surface Book Dedicated GPU version.

![capture20160210080809428](https://cloud.githubusercontent.com/assets/17053210/12948033/8441fca4-cfcd-11e5-8bb1-1525905328db.png)

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
