### ISSUE TITLE
German language file

### ISSUE THREAD

**Issue by joelstudler** [kmscode/mRemote3G#60]
Your German language file for mRemote3G has at least one issue:
https://github.com/kmscode/mRemote3G/blob/develop/mRemoteV1/Language/Language.de.resx#L1921

should be: 
    <value>Tabs &amp;&amp; Panels</value>

You can also add me as a collaborator for the german language file...

**Comment by kmscode** [comment]
@joelstudler 

Thanks for the report. If you don't mind... How about a pull request to the mRemoteNG repo with any langauge corrections. Would like to get updated localization files where we can! See my most recent commit for details:
https://github.com/kmscode/mRemote3G/blob/develop/README.md
