### ISSUE TITLE
Import from backup

### ISSUE THREAD

**Issue by mighelon** [kmscode/mRemote3G#61]
Hi,
after the import mRemote3G puts all the folders into a new "root" hierarchy creating a folder with the name of the export file. It would be great if you can select to put all the folders into the default root "Connections".
Moreover, backup/import process doesn't save External Tools. It would be great to have it inside.

Thank you!
Mike

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
