### ISSUE TITLE
Cannot delete folder

### ISSUE THREAD

**Issue by mighelon** [kmscode/mRemote3G#62]
Hi,
honestly I don't know when this issue appear because usually I create folders, rarely I delete them. However, I've found I cannot remove folder containing some connections, I indeed can delete a single connection.
If I try to remove the folder, mRemote3G removes some connections inside (not all) but not the folder itself.

Let me know.
Thank you!

**Comment by kmscode** [comment]
Could you please provide the mremote3g.log?

**Comment by mighelon** [comment]
yes, sure
[mRemote3G.zip](https://github.com/kmscode/mRemote3G/files/261789/mRemote3G.zip)
here it is

**Comment by mighelon** [comment]
yes, sure
here it is

**Comment by mighelon** [comment]
sorry, I've click on close for mistake, I had firefox stucked....

**Comment by kmscode** [comment]
This should be fixed in [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG):
https://mremoteng.atlassian.net/browse/MR-836
