### ISSUE TITLE
Request: Linux support

### ISSUE THREAD

**Issue by waqark3389** [kmscode/mRemote3G#63]
This is by far the best SSH connection manager out there. I could not find another with panels as well as tabs underneath them. 
Are there any plans to make this work in Linux, I tried wine, I tried mono. Too many native windows calls! 

Please?

**Comment by kmscode** [comment]
Sorry. No current plans to port to Linux or to ensure Linux functionality via wine/mono. Will leave this open as an enhancement though.

**Comment by kmscode** [comment]
All dev efforts have shifted to [mRemoteNG](https://github.com/mRemoteNG/mRemoteNG)

Please see https://mremoteng.atlassian.net/browse/MR-723
