### ISSUE TITLE
Can't submit password containing "%" to external program

### ISSUE THREAD

**Issue by Frank-Maier** [kmscode/mRemote3G#64]
Hello, first of all thank you very much for this great piece of software.

I use mremote to connect to different ESX Servers. So i have the following parameter in the vsphere entry in the external programs. "-s %Hostname% -u %Username% -p %Password%"

The authentification only works if the password don't contains "%".

In the old mRemoteNG the connect works perfect regardless of the percent sign in the password.

Do you have any idea to solve this issue?

Thanks a lot.

Frank

**Comment by kmscode** [comment]
Thanks for the report. Please try mRemoteNG 1.74 to see if this problem still occurs. See my most recent commit for details:
https://github.com/kmscode/mRemote3G/blob/develop/README.md

**Comment by Frank-Maier** [comment]
Hi, thanks for your answer. The problem still exist.

**Comment by kmscode** [comment]
Will look into it. Looks like there are problems with other characters as well:
https://mremoteng.atlassian.net/browse/MR-704

**Comment by kmscode** [comment]
New bug report: https://mremoteng.atlassian.net/browse/MR-857

No ETA for a fix at this time.

**Comment by Frank-Maier** [comment]
I work in a software company and perhabs someone could look over the code. Please give me some hints where to start searching for the bug in the code.

**Comment by kmscode** [comment]
Again, all work on 3G has ceased so going to NG is highly recommended. Looks like the code in question is here:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Tools/ArgumentParser.cs

Details on the build environment used can be found here:
https://mremoteng.atlassian.net/wiki/display/MR/Setting+up+your+development+environment

Feel free to review and submit pull requests against the https://github.com/mRemoteNG/mRemoteNG develop branch.

Thanks!!!

**Comment by Frank-Maier** [comment]
thanks for your help. I know that 3G is ceased. I wrote only for overview in my old thread. One of our C# Developers tries to find out the bug.

-----Ursprüngliche Nachricht-----
Von: Sean Kaim [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. Juni 2016 15:26
An: kmscode/mRemote3G
Cc: Frank-Maier; Comment
Betreff: Re: [kmscode/mRemote3G] Can't submit password containing "%" to external program (#64)

Again, all work on 3G has ceased so going to NG is highly recommended. Looks like the code in question is here:
https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Tools/ArgumentParser.cs

Details on the build environment used can be found here:
https://mremoteng.atlassian.net/wiki/display/MR/Setting+up+your+development+environment

Feel free to review and submit pull requests against the https://github.com/mRemoteNG/mRemoteNG develop branch.

Thanks!!!

**Comment by Frank-Maier** [comment]
We found it!
Comment the follwing lines solve the problem.

ArgumentParser.cs, Line 141, 142
//if (escape == EscapeType.All | escape == EscapeType.ShellMetacharacters)
//replacementValue = CommandLineArguments.EscapeShellMetacharacters(replacementValue);

Do you forcast any bad sideeffects?

**Comment by kmscode** [comment]
That will break functionality as described in the [ExternalTools.htm](https://github.com/mRemoteNG/mRemoteNG/blob/develop/mRemoteV1/Resources/Help/ExternalTools.htm) file.

Looking into the code and the documentation further, looks like you might be able to avoid escaping characters:

    To disable both argument splitting and shell metacharacter escaping for a variable, precede its name with an exclamation point (!). For example, %!USERFIELD%.

So in your case:

    %!PASSWORD%

Otherwise, if that doesn't work I would maybe recommend checking if we are attempting to escape the password variable and then continuing the loop... Without testing... I would think this could be done on line 104:

variableName = input.Substring(variableNameStart, variableNameLength);
if (variableName.Equals("%password%", StringComparison.InvariantCultureIgnoreCase))
                    continue;

Again, completely untested.  This could also have other ramifications...

Let me know if "%!PASSWORD%" works.

**Comment by Frank-Maier** [comment]
With the vSphere Client "%!PASSWORD%" works. But with the external program WinSCP it don't works.

**Comment by Frank-Maier** [comment]
Winscp have an generell encoding problem....
https://winscp.net/eng/docs/session_url#fn3

%!PASSWORD% works with all other special chars in WINCSP.

**Comment by Frank-Maier** [comment]
To complete this thread the complete External Tool Properties:

vsphere
C:\Program Files (x86)\VMware\Infrastructure\Virtual Infrastructure Client\Launcher\VpxClient.exe
-s %Hostname% -u %Username% -p %!PASSWORD% -locale en-us

WINSCP
C:\Program Files (x86)\WinSCP\WinSCP.exe
scp://%Username%:%!Password%@%Hostname%/

**Comment by kmscode** [comment]
Per https://winscp.net/eng/docs/session_url#fn3 :

> To escape these characters, you can wrap whole session URL to double-quotes (") or encode the characters as shown above. 

So:
C:\Program Files (x86)\WinSCP\WinSCP.exe "scp://%Username%:%!Password%@%Hostname%/"
