### ISSUE TITLE
Can't submit password containing "%" to external program

### ISSUE THREAD

**Issue by Frank-Maier** [kmscode/mRemote3G#67]
In Version 1.74 of mRemoteNG the problem still exist... also with WinSCP. 

A fix would be reallly nice. Thank's for your great work.

https://github.com/kmscode/mRemote3G/issues/64#issuecomment-222818951

**Comment by kmscode** [comment]
Per https://winscp.net/eng/docs/session_url#fn3 :

>To escape these characters, you can wrap whole session URL to double-quotes (") or encode the characters as shown above.

So:
C:\Program Files (x86)\WinSCP\WinSCP.exe "scp://%Username%:%!Password%@%Hostname%/"
