### ISSUE TITLE
inherit settings lost

### ISSUE THREAD

**Issue by federicozanardi** [kmscode/mRemote3G#69]
imported confcon from last 3G lost a lot of inherited configurations
cannot be fixed manually

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
