### ISSUE TITLE
support use of a ssh gateway

### ISSUE THREAD

**Issue by rosset** [kmscode/mRemote3G#7]
Hi, can you please add support to use a ssh gateway instead of only RDP gateway?

This functionally is available in mobaxterm and there are some workarounds for mremoteng here http://forum.mremoteng.org/viewtopic.php?f=3&t=2177

**Comment by kaymer327** [comment]
I'd have to look into this further... 

But in theory you should be able to configure a saved session within PuTTY (and PuTTYNG) directly to do this:
http://tartarus.org/~simon/putty-snapshots/htmldoc/Chapter4.html#config-proxy

http://tartarus.org/~simon/putty-snapshots/htmldoc/Chapter3.html#using-cmdline-ncmode

You can select the session to use directly within mRemote. If I'm reading the PuTTY doc correctly, you would configure mRemote to the "desired" host as normal. But choose the "gateway" session that you would need to create. In the gateway session, you would configure it as a local proxy with the appropriate plink command. 

This would require the full [PuTTY](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) package to be installed and the command should likely be the full path to plink.exe.

Assuming that you only have 1 gateway server (or only a few gateway servers) you can setup the saved PuTTY session(s) and then use inheritance from a folder to have each host connect via the proper gateway with minimal effort within mRemote itself.

If I come up with more solid instructions, then maybe I'll start a Wiki on this GitHub project page and document it fully.

**Comment by mbirth** [comment]
[This](#issuecomment-169716589) is what I'm using. I have a PuTTY-session called "SSH-Proxy" with the following in Connection --> Proxy --> Telnet command, or local proxy command:

    U:\Apps\mRemoteNG\plink.exe -ssh user@proxyhost.com -agent -nc %host:%port

Auth is via key so I don't get asked for two passwords.

Works even with the "old" original mRemoteNG.

**Comment by kmscode** [comment]
Awesome! Thanks!!! I haven't had a chance to test this myself. Glad to hear that it works! I'll see about posting a wiki page on this topic.
