### ISSUE TITLE
Freeze of Computer with Win 10

### ISSUE THREAD

**Issue by trompi** [kmscode/mRemote3G#8]
Hello,

Time to time when a RDP session get disconnected or cannot connect or long time to load it's freeze my computer for few minutes without the possibility to do anything ( never get the case with windows 7 before) 

I setup the last version you release this morning but I get the issue again .. I put a screenshot of what I can see in the Windows logs:
![tna](https://cloud.githubusercontent.com/assets/16664586/12261243/1feaf9ea-b920-11e5-9315-0c6f6c8ce7a8.png)

and

![tna2](https://cloud.githubusercontent.com/assets/16664586/12261246/2582d224-b920-11e5-839f-aa1beaede960.png)

if you need more information or find a way to fix it it will be great,

Anyway thanks for the support on this very good software.

Regards,

**Comment by kmscode** [comment]
Please provide me with the mRemote3G.log (which should be located in the same directory as the .exe).

However, I have a feeling that this is related to the KeyBoard Shortcut listener code which I disabled in commit: f2d4478b7fd32cb1ef2bc5afc98cfc3666ed3faf

I was going to try to fix a few other things first, but due to this report, I hope to have a 1.93 release out later this week, early next week with that code removed (see the commit for details) -- depending on what I see in the log.

Thanks.

**Comment by trompi** [comment]
Hello,

I put the log file on attachment, 

[mRemote3G.txt](https://github.com/kmscode/mRemote3G/files/90310/mRemote3G.txt)

not sure if you will find anything useful, I was wondering if it cannot be linked to the garbage collector as the module use is clr.dll ...

Anyway if you need anything else, please let me know.

Regards,
Trompi

**Comment by kmscode** [comment]
Looks like you're running into a known issue with the .NET Framework:
https://support.microsoft.com/en-us/kb/2640103

I suggest that you update your .NET Framework to resolve this problem.

**Comment by kmscode** [comment]
Looks like the versions are different (though the "30319" build is still reference even on Win 10). This might be related to #10

**Comment by kmscode** [comment]
@trompi Give [1.94.1](https://github.com/kmscode/mRemote3G/releases/tag/1.94.1) a whirl. Let me know if you're still having problems.

**Comment by trompi** [comment]
Hello,

Thanks for the information, I setup it this morning, and so far no more issue :-)
Will let you know if it's freeze again my laptop.

Thanks

**Comment by federicozanardi** [comment]
I have the issue on 1.94.1
less than in prev version, but still occurs

**Comment by kolbyg** [comment]
Same issue here. Doesn't happen too often but when it does it makes the computer completely unusable for around 5 minutes.

**Comment by TRNIntegrations** [comment]
Same issue here.  Opened a 5th RDP window, lost control of my pc for about 10-15 mins.  Force close the app, re-open it, re-open all my tabs, no problems.

**Comment by trompi** [comment]
Hello,

After looking at the error and code, I find out the solution for this problem, check that in the configuration of your RDP the bitmap Cache is disable, if not you will get these issue with the pc freezing out for 5 to 10 min ...

**Comment by kmscode** [comment]
@trompi Thanks for the update!

The cache disable trick worked for other users when having problems opening a number of RDP connections (sometimes it was as low as 5 other times it was 20 or more). The connections would just error out, but not freeze.
