### ISSUE TITLE
connection inheritance not working

### ISSUE THREAD

**Issue by thecosmictrickster** [kmscode/mRemote3G#9]
I have a folder with Use CredSSP set to Yes. I have a connection in the folder set to inherit this setting. However, the setting is not inherited. I have tried changeing the setting at the folder level, restarting, changing it back, restarting. Still not inherited. If I turn inheritance off for Use CredSSP on the connection, the value is showing as No, even though the parent folder still shows Yes. I tried turning off inheritance, changing the value to Yes, restarting, and setting inheritance back on. Still not inherited (folder still set to Yes as well).

**Comment by thecosmictrickster** [comment]
More information - as described, I have a folder & connection; I also have a subfolder. So the structure is:
ParentFolder
 ->SubFolder
 ->Connection

The Connection should be inheriting settings from ParentFolder. However, it appears to be inheriting [at least] Use CredSSP setting from SubFolder; when I change the setting on SubFolder, Connection picks up that setting.

**Comment by kmscode** [comment]
Do all other setting get inherited from from the parent folder?

**Comment by thecosmictrickster** [comment]
I'll have to do some more testing. This seems to have been an issue in mRemoteNG as well - I just hadn't encountered it before.

**Comment by kmscode** [comment]
I've been using the mRemoteNG 1.72 Portable version as my basis for comparison (despite forking the latest code rmcardle/mRemoteNG - which was effectively an unreleased 1.73 Beta2 version). I haven't had a chance to test this one in either 1.72 or my current code base. Regardless, if it's not working in my current release I'll look into if it should work or if it's fixable.

Let me know if you have any other test results to report.

**Comment by thecosmictrickster** [comment]
Definitely affects username, password, domain, port, disk drive mapping.

**Comment by thecosmictrickster** [comment]
Subfolders do not seem to inherit from subfolders above them but from the parent folder as intended. So summary:

ParentFolder
  ->Subfolder1
  ->Subfolder2
     -> SF1Connection1
  ->Subfolder3
  ->PFConnection1
  ->PFConnection2

PFConnection1 & PFConnection2 inherit from Subfolder3 instead of ParentFolder (unexpected behaviour). 
Subfolder3 inherits from ParentFolder not Subfolder2 (expected behaviour)

**Comment by kmscode** [comment]
So I'm a little confused... Screenshot maybe?

Are any of the Subfolders nested? Or are all Subfolders children of parent folder?

**Comment by kmscode** [comment]
Or better yet, create a dummy connections file that shows the problem and attach it! :smile:

**Comment by thecosmictrickster** [comment]
See attached. PFConnection1 is inheriting from SubFolder3 but not ParentFolder. Oddly, when I was creating it, inheritance seemed to be working as expected, until I restarted the program.
[confCons.xml.txt](https://github.com/kmscode/mRemote3G/files/91310/confCons.xml.txt)

**Comment by seeyainhell** [comment]
Hi kmscode,

I second this issue. Please take a look at screenshot 
![mremote3ginheritanceissue](https://cloud.githubusercontent.com/assets/16734241/12373013/cd57dfe0-bc62-11e5-9a54-37cb9c9fed2a.PNG)

My case: jo folder is a parent with default protocol RDP and domain credentials, so I expect to connect to winlabdc1 via RDP.
*nix subfolder has very little inherited from jo, main protocol there is SSHv2 to get putty connected.

Yesterday I've been working fine with all those hosts created initially, today I initiated connection to the whole jo folder and got 3 putty connections, with 1 being relevant frelabgate1, two others timing out as Windows doesn't run ssh natively.

So despite the tree diagram connecting win* hosts to jo folder, they actually inherit settings (well, protocol at least) from *nix.

**Comment by kmscode** [comment]
I stepped through the code a few times using the example confcons.xml.txt attached by @thecosmictrickster - It looks like it provides the correct parent folder, then after returning (with what appeared to be the correct info), the values are now pointing to the wrong subfulder3. I'm still not yet too familiar with this area of code (and to be very honest, I wasn't feeling well when I stepped through it, so not sure if I was delirious or not).  :confused:

I'll keep at it... :smile:

**Comment by jcefoli** [comment]
Is this the same issue as this? https://mremoteng.atlassian.net/browse/MR-651

I had this happen to me in mRemoteNG. Now, I cannot reproduce it, but I didn't test that thoroughly.

**Comment by seeyainhell** [comment]
Exactly that issue, affecting any settings inherited, not limited to
accounts.

**Comment by kmscode** [comment]
@jcefoli Yes, looks like this is the same bug report that you referenced.

**Comment by kmscode** [comment]
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!
